server:
  port: 8080

spring:
  config:
    import: env.properties
  application:
    name: testApi
  datasource:
    driver-class-name: ${DB_DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update